export const GENERATE_BOARD = 'GENERATE_BOARD'
export const CHECK_NEIGHBOURS = 'CHECK_NEIGHBOURS'
export const SQUARES_TO_MOVE = 'SQUARES_TO_MOVE'
export const SQUARES_TO_REGENERATE = 'SQUARES_TO_REGENERATE'